### ISSUE TITLE
Supporting another Zookeeper cluster to store state

### ISSUE THREAD

**Issue by a-nldisr** [Intel-bigdata/ceph-mesos#29]
From the documentation i found that there is the option to configure a "zookeeper" besides the master, is this to support other zookeeper clusters to store the ceph state than the mesos masters zookeeper cluster?

**Comment by tangzhankun** [comment]
@a-nldisr 
yes. It belongs to the reconciliation feature. We plan to do this in future, but it was not implement yet.
