### ISSUE TITLE
Journal device selection for OSD's

### ISSUE THREAD

**Issue by a-nldisr** [Intel-bigdata/ceph-mesos#30]
From the documentation i have found that i can create a list of journal devices and OSD devices. 
Is it possible to link an specific OSD to a specific journal device? Or are there plans to support this?

```
osddevs:
  - sdc
jnldevs:    []
```

Use cases: 
In our setups we have chosen to only support 5 OSD's per single journal disk because of the bandwidth of the journal disk, we therefor limit the amount of OSD's per journal disk. How would this be handled in above setup?

Since us operators are creatures of habbit we attach the 1-5 OSD's to journal disk 1 and the other 6-10 OSD's to journal disk 2. It is easier to spot patterns this way and keep sanity in environments with 300+ OSD's.

**Comment by tangzhankun** [comment]
@a-nldisr 
Thanks for the suggestion. It's not possible to specify arbitrary relation of OSDs and journal devices in current config file. We can do this if there is a well defined format. But there is no plan right now.

For your use case, I think current implementation can support the pattern. Ceph-Mesos have an hard-coded journal disk partition number which is 4 now (src/executor/DiskExecutor.hpp) that haven't been exposed through this configuration(will fix this soon). You can do this if you want it now:
1. Change the  jnlPartitionCount to 5 in src/executor/DiskExecutor.hpp
2. Build Ceph-Mesos
3. Populate cephmesos.yml like this:
```sh
...
osddevs:
  - sdb
  - sdc
  - sdd
  - sde
  - sdf
  - sdg
  - sdh
  - sdi
  - sdj
  - sdl
jnldevs:
  - sdm
  - sdn
```
In such configuration, Ceph-Mesos will try to use sd[g-l] with sdn[1-5] and sd[b-f] with sdm[1-5].

BTW, we are doing performance testing now to make sure that ceph in container can work well. So our feature is quite basic for now. If any question, feel free to ask. :)
