### ISSUE TITLE
add/clarify how to create/use metadata servers ceph-mds?

### ISSUE THREAD

**Issue by fernandosanchezmunoz** [Intel-bigdata/ceph-mesos#37]
This is fantastic work!!

I'm wondering whether metadata servers for use with CephFS are supported? If so, how would they be created/handled?

thanks

**Comment by tangzhankun** [comment]
@fernandosanchezmunoz, Ceph MDS is not supported yet. We have no cycle to do this for now, sorry for this. welcome discussion and contribute on this.

**Comment by fernandosanchezmunoz** [comment]
Thanks for the clarification @tangzhankun.
